# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('car_type', models.CharField(max_length=200)),
                ('car_price', models.FloatField()),
                ('car_number', models.IntegerField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_des', models.CharField(max_length=250)),
                ('hotel_rank', models.IntegerField()),
                ('hotel_review', models.CharField(max_length=250)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.City')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=200)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('room_price', models.FloatField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Hotel')),
            ],
        ),
    ]
