# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_des',
            field=models.TextField(blank=True, null=True, verbose_name='hotel description'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
