# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=200)),
                ('city_rank', models.IntegerField()),
                ('city_des', models.TextField(blank=True, null=True, verbose_name='City Description')),
                ('city_long', models.FloatField(verbose_name='City Longitude')),
                ('city_lat', models.FloatField(verbose_name='City Latitude')),
                ('city_image', models.ImageField(blank=True, upload_to='cities_images')),
            ],
        ),
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('cont_id', models.AutoField(primary_key=True, serialize=False)),
                ('cont_name', models.CharField(max_length=200, verbose_name='Continent Name')),
                ('cont_image', models.ImageField(blank=True, upload_to='conts_images', verbose_name='Continent Image')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=200)),
                ('country_rank', models.IntegerField()),
                ('country_image', models.ImageField(blank=True, upload_to='countries_images')),
                ('cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Continents', verbose_name='Continent Name')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=200)),
                ('site_des', models.TextField(blank=True, null=True, verbose_name='site description')),
                ('site_rank', models.IntegerField()),
                ('site_review', models.CharField(max_length=250)),
                ('site_image', models.ImageField(blank=True, upload_to='sities_images')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Country', verbose_name='Country'),
        ),
    ]
