# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continents',
            name='cont_des',
            field=models.TextField(blank=True, null=True, verbose_name='Continent Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_des',
            field=models.TextField(blank=True, null=True, verbose_name='country Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_lat',
            field=models.FloatField(default=23.6, verbose_name='country Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_long',
            field=models.FloatField(default=23.7, verbose_name='country Longitude'),
            preserve_default=False,
        ),
    ]
