# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_des',
            field=models.TextField(blank=True, null=True, verbose_name='City Description'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_lat',
            field=models.FloatField(verbose_name='City Latitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_long',
            field=models.FloatField(verbose_name='City Longitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='continents',
            name='cont_name',
            field=models.CharField(max_length=200, verbose_name='Continent Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='cont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Continents', verbose_name='Continent Name'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_des',
            field=models.TextField(blank=True, null=True, verbose_name='site description'),
        ),
    ]
