# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190216_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_image',
            field=models.ImageField(blank=True, upload_to='cities_images'),
        ),
        migrations.AddField(
            model_name='continents',
            name='cont_image',
            field=models.ImageField(blank=True, upload_to='conts_images', verbose_name='Continent Image'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_image',
            field=models.ImageField(blank=True, upload_to='sities_images'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_image',
            field=models.ImageField(blank=True, upload_to='countries_images'),
        ),
    ]
