# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-15 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(default=1)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Car')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Country')),
                ('loc_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location from+', to='reservation.Location')),
                ('loc_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location to+', to='reservation.Location')),
            ],
        ),
        migrations.CreateModel(
            name='HotelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(default=1)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('num_of_person', models.PositiveIntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Hotel')),
            ],
        ),
    ]
