# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-17 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carhistory',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='hotelhistory',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.RemoveField(
            model_name='carhistory',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='hotelhistory',
            name='user_id',
        ),
    ]
