# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_title',
            field=models.TextField(default='TITLE', max_length=10000),
        ),
    ]
